channels:
- defaults
- menpo
- omnia
dependencies:
- future
- numpy
- scipy
- ipython
- ipyparallel
- jupyter
- matplotlib
- scikit-image
- scikit-learn
- h5py
- cython
- spyder
- nose
- bokeh
- tensorflow
- keras
- tqdm
- opencv3
- cvxpy
- pip:
  - tifffile==0.12.1
  - peakutils
